# Generated by Django 6.1 on 2026-08-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='default.webp', null=True, upload_to='avatars/'),
        ),
    ]
