# Generated by Django 6.1 on 2026-08-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='social_links',
            new_name='social',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='user',
        ),
    ]
